spring.application.name=transaction-service

spring.application.name=transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/txguard
spring.datasource.username=postgres
spring.datasource.password=utpal0209

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=0209